name: Build and deploy if tagged

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Build
        run: |
          npm install
          npm run webapp:build
       
      - name: Deploy if tagged
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: webapp/dist
          token: ${{ secrets.DEPLOY_TOKEN }}
          repository-name: zopieux/zopieux.github.io
          branch: master
          target-folder: notes
          commit-message: Deploy notes.
          git-config-name: Alexandre Macabies
          git-config-email: <web+oss@zopieux.com>
