name: Build and deploy

on: push

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Build
        run: |
          npm install
          npm run webapp:build

      - name: Deploy if tagged
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: webapp/dist
          token: ${{ secrets.DEPLOY_TOKEN }}
          repository-name: zopieux/zopieux.github.io
          branch: master
          target-folder: notes
          commit-message: Deploy notes.
          git-config-name: Alexandre Macabies
          git-config-email: <web+oss@zopieux.com>
